import Head from "next/head";
import { motion } from "framer-motion";
import About from "../components/About";
import Projects from "../components/Projects";
import Skills from "../components/Skills";
import Link from "next/link";

const myAnimation = {
  offscreen: { opacity: 0 },
  onscreen: { opacity: 1 },
};

export default function Home() {
  return (
    <div className="py-40">
      <Head>
        <title>Mugwira / Portifolio </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <motion.div
        initial={"offscreen"}
        animate={"onscreen"}
        transition={{ staggerChildren: 1 }}
        className="mb-64 w-1/2 text-center mx-auto  "
      >
        <motion.h2 variants={myAnimation} className="text-6xl mb-6 ">
          Welcome, I am Mugwira Matsveru
        </motion.h2>
        <motion.h4 className="text-4xl mb-3 font-semibold text-blue-500">
          Frontend Developer
        </motion.h4>
        <motion.p className="text-gray-700 text-center text-sm leading-8 mb-12">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi placeat
          voluptas inventore ab facilis beatae? Accusantium vel beatae, cumque
          consequatur assumenda ad minus odit dicta deleniti. Laborum
          perspiciatis est saepe.
        </motion.p>
        <Link href="/portfolio/about">
          <motion.a
            variants={myAnimation}
            className="border px-12 bg-navy hover:bg-navyLight hover:cursor-pointer text-white py-3 font-semibold rounded-full"
          >
            View More
          </motion.a>
        </Link>
      </motion.div>
      <About />
      <Skills />
      <Projects />
    </div>
  );
}
